baseURL = "https://scdhub.org"
languageCode = "en"
defaultContentLanguage = "en"
title = "SCD Hub"
theme = "dream"

copyright = '2021 SCD Hub <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。<br /><br />背景使用了 <a href="https://www.pexels.com/zh-cn/" target="_blank">Pexels</a> 上 <a href="https://www.pexels.com/zh-cn/@minan1398" target="_blank">Min An</a> 拍摄的<a href="https://www.pexels.com/zh-cn/photo/1454794/" target="_blank">图片</a>。'

googleAnalytics = "UA-98295641-1"

disqusShortname = "scdhub"

enableRobotsTXT = true

hasCJKLanguage = true

# Paginate = 6

[outputs]
  home = ["HTML", "RSS", "JSON"]

# https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  background = "#fff"
  backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  # dark mode
  # defaultDark = true
  # backgroundDark = "#222"
  backgroundImageDark = "/me/background.jpg"
  darkLinkColor = "darkseagreen"
  # darkNav = true
  # dark404 = true

  images = ["me/background.jpg"]

  author = "Greg Willson"
  description = "SCD Hub is dedicated to connecting people together to empower one another with pertinent information about how to address complex social and environmetnal problems. In 2021 we are heavily invested in documenting solutions and case studies of how Municipal Solid Waste, Drinking Water, and Waste Water issues can be addressed at the local level. "
  avatar = "/scdhub/scdhub.svg"
  headerTitle = "SCD Hub"
  motto = "It’s better to set off right away instead of feeling the road is difficult"
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = "Sustainable Community Development means honoring our commuitments to ourselves that we live a good life, while recognizing that we must consider to future generations."

  rss = true

  utterancesRepo = "g1eny0ung/g1eny0ung.github.io"

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""

  email = "acmeideal@gmail.com"
  twitter = "scdhub"
  facebook = "sustainable-community-development-hub"
  instagram = "ecocitylearningportal"
  # mastodon = ""
  linkedin = "ecocity"
  github = "sustainablecommunitydevelopmenthub"
  stackoverflow = "5676489/g1eny0ung"
  codepen = "biomassives"

  siteStartYear = 2016

  favicon = "/favicon.ico"

  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["Drinking water", "Wastewater and Sewage", "Municipal Solid Waste"]
  highlightjsTheme = "tomorrow"
  highlightjsThemeDark = "tomorrow-night"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true
  # hasTwitterEmbed = true

  [params.advanced]
    customCSS = ["css/custom.css"]
    customJS = []

